index:

    r: Region

    a: Activity

    c: Commodity

    s: Sector

    k: Satellite account

    f: Factor of production

    n: Consumption category



nomenclature:

  e: e

  E: E

  X: X

  EY: EY

  VY: VY

  Y: Y

  y: y

  V: V

  v: v

  F: F

  f: f

  M: M

  m: m

  b: b

  g: g

  w: w

  p: p

  z: z

  Z: Z

  u: u

  U: U

  s: s

  S: S


compute:

  compute_method: auto

  linear_solver: scipy

  linear_strategy: auto

  auto_w_memory_fraction: 0.25

  auto_w_overhead_factor: 3.0
