index:
  r: Region
  a: Activity
  c: Commodity
  s: Sector
  k: Satellite account
  f: Factor of production
  n: Consumption category
index_aliases:
  r:
  - region
  - regions
  - country
  - countries
  a:
  - activity
  - activities
  - activitiy
  - Industry
  - Industries
  c:
  - commodity
  - commodities
  - product
  - products
  s:
  - sector
  - sectors
  - industry
  - industries
  k:
  - satellite account
  - satellite accounts
  - extension
  - extensions
  - Satellite
  - Satellites
  - Satellite_accounts
  f:
  - factor of production
  - factors of production
  - value added
  - Factors
  - factor
  - Factors_of_production
  - factor_of_production
  n:
  - consumption category
  - consumption categories
  - final demand
  - final demand category
  - final demand categories
  - demand categories
  - Consumption_category
  - Consumption_categories
  - demand_categories
nomenclature:
  e: e
  E: E
  X: X
  EY: EY
  VY: VY
  Y: Y
  y: y
  V: V
  v: v
  F: F
  f: f
  M: M
  m: m
  b: b
  bu: bu
  bs: bs
  g: g
  gcc: gcc
  gca: gca
  gac: gac
  gaa: gaa
  w: w
  p: p
  z: z
  Z: Z
  u: u
  U: U
  s: s
  S: S
compute:
  compute_method: auto
  linear_solver: scipy
  linear_strategy: auto
  auto_w_memory_fraction: 0.25
  auto_w_overhead_factor: 3.0
