name: mario
channels:
  - conda-forge
dependencies:
  - python>=3.11
  - numpy==2.1.1
  - pandas==3.0.2
  - plotly
  - tabulate
  - openpyxl==3.1.5
  - pint==0.25.3
  - ipython>=8.27.0
  - pandoc
  - pybtex
  - sphinx
  - pydata-sphinx-theme
  - nbsphinx
  - sphinx-copybutton
  - myst-parser
  - nbconvert
  - nbformat
  - sphinxcontrib-bibtex
  - pyyaml
  - country_converter
  - xlsxwriter==3.2.9
  - pytest
  - scipy
  - h5py
  - pyarrow>=17
  - pyxlsb
  - pip
  - pip:
      - pymrio
      - cvxlab>=1.0.0b1
